server:
  port: 8083
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.worldwire.model
spring:
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: 47.104.201.53
    port: 6379
    password: 123456QWEasd
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
    timeout: 0
multipart:
  maxFileSize: 50Mb
qq:
  appid: 1106875040
  appkey: xy0YfT0z8I2JcN44
---
spring:
  profile: online
  datasource:
    name: worldwire
    url: jdbc:mysql://101.200.137.78:3306/worldwire
    username: root
    password: 123456aA!!
    driver-class-name: com.mysql.jdbc.Driver
file:
  basedir: data\worldwire\file\
---
spring:
  profiles: test
  datasource:
    name: worldwire
    url: jdbc:mysql://127.0.0.1:3306/worldwire
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
file:
  basedir: D:\data\worldwire\file\