server:
  port: 8083
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.worldwire.model
spring:
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .html
    template-loader-path: classpath:/templates
  redis:
    database: 0
    host: 47.104.201.53
    port: 6379
    password: 123456QWEasd
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
    timeout: 0
multipart:
  maxFileSize: 50Mb
qq:
  appid: 1106875040
  appkey: xy0YfT0z8I2JcN44
---
spring:
  profile: online
  datasource:
    name: worldwire
    url: jdbc:mysql://127.0.0.1:3306/worldwire
    username: root
    password: 123456aA!!
    driver-class-name: com.mysql.jdbc.Driver
file:
  basedir: data\worldwire\file\
---
spring:
  profiles: test
  datasource:
    name: worldwire
    url: jdbc:mysql://127.0.0.1:3306/worldwire
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
file:
  basedir: D:\data\worldwire\file\