server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.worldwire.model
spring:
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .html
    template-loader-path: classpath:/templates
  redis:
    database: 0
    host: 101.200.137.78
    port: 6379
    password: 123456QWEasd
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
    timeout: 0
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
multipart:
  maxFileSize: 50Mb
qq:
  appid: 1106875040
  appkey: xy0YfT0z8I2JcN44
wx:
  appid: wxb2a2591be835d810
  appsecret: 293443b83fb49842e02b3100551a5373
---
spring:
  profile: online
  datasource:
    name: worldwire
    url: jdbc:mysql://127.0.0.1:3306/worldwire
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
file:
  basedir: /data/worldwire/file/
---
spring:
  profiles: test
  datasource:
    name: worldwire
    url: jdbc:mysql://127.0.0.1:3306/worldwire
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
file:
  basedir: D:\data\worldwire\file\